# Generated by Django 5.2.6 on 2025-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
