# Generated by Django 5.2.6 on 2025-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_ava',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
